### PR TITLE
Create sergoio0704-kmrnoff.json

### PR DESCRIPTION
**Pull request by sergoio0704**

### CODE REVIEW

**Review by TarekAwwad — APPROVED** [review]
Thank you for contributing! The contribution format is valid :+1:
The contribution content will be reviewed later.

**Review by TarekAwwad — CHANGES_REQUESTED** [review]
Thank you for contributing! The contribution format seems invalid :slightly_frowning_face:

Please feel free to check the contribution instruction in the [readme](https://github.com/KiFoundation/ki-testnet-challenge/tree/main/contributions/relayers) and to commit the necessary changes to this PR.

The contribution content will be reviewed later.

**Comment by sergoio0704** [comment]
> Thank you for contributing! The contribution format seems invalid 🙁
> 
> Please feel free to check the contribution instruction in the [readme](https://github.com/KiFoundation/ki-testnet-challenge/tree/main/contributions/relayers) and to commit the necessary changes to this PR.
> 
> The contribution content will be reviewed later.



> Спасибо за участие! Формат публикации кажется недействительным🙁
> 
> Пожалуйста, не стесняйтесь проверять инструкции по вкладу в [readme](https://github.com/KiFoundation/ki-testnet-challenge/tree/main/contributions/relayers) и вносить необходимые изменения в этот PR.
> 
> Содержание публикации будет рассмотрено позже.

Sorry! Can you tell me what the mistake is?

**Comment by TarekAwwad** [comment]
Please add your file in the correct location (contributions/relayers)

**Comment by sergoio0704** [comment]
> Please add your file in the correct location (contributions/relayers)

Thanks for the tip! I have moved the file to the specified directory

**Review by TarekAwwad — APPROVED** [review]

**Pull request merged**
