### PR TITLE
Create vinovod-cosinusnode.json

### PR DESCRIPTION
**Pull request by vinovod**

### CODE REVIEW

**Review by TarekAwwad — CHANGES_REQUESTED** [review]
Thank you for contributing! The contribution format seems invalid :slightly_frowning_face:

Please feel free to check the contribution instruction in the [readme](https://github.com/KiFoundation/ki-testnet-challenge/tree/main/contributions/relayers) and to commit the necessary changes to this PR.

The contribution content will be reviewed later.

**Comment by vinovod** [comment]
Seems done or I didn't get what is wrong with PR. Fixed add comment in JSON

**Review by vinovod — COMMENTED** [review]
Fixed add comments

**Comment by TarekAwwad** [comment]
Please do not remove the template file <github_username>-<moniker>.json.

**Comment by vinovod** [comment]
Just have made a new PR — https://github.com/KiFoundation/ki-testnet-challenge/pull/67
Sorry for that.

This PR is closing

**Pull request closed without merging**
