### PR TITLE
Confuzerpy-confuzer.json

### PR DESCRIPTION
**Pull request by Confuzerpy**

### CODE REVIEW

**Review by TarekAwwad — CHANGES_REQUESTED** [review]
Thank you for contributing! The contribution format seems invalid :slightly_frowning_face:

Please feel free to check the contribution instruction in the [readme](https://github.com/KiFoundation/ki-testnet-challenge/tree/main/contributions/relayers) and to commit the necessary changes to this PR.

The contribution content will be reviewed later.

**Comment by Confuzerpy** [comment]
Hello! If something wrong, please just point me where is the error. Thanks!

**Comment by TarekAwwad** [comment]
Please do not remove the template file `<github_username>-<moniker>.json`.

**Comment by Confuzerpy** [comment]
o my god.... thought i should use ```<github_username>-<moniker>.json``` as a template.

**Review by TarekAwwad — APPROVED** [review]

**Pull request merged**
