### PR TITLE
Add qf3l3k-qf3l3k.json

### PR DESCRIPTION
**Pull request by qf3l3k**

### CODE REVIEW

**Review by qf3l3k — COMMENTED** [review]
Updated path to docu.

**Review by TarekAwwad — CHANGES_REQUESTED** [review]
Thank you for contributing! The contribution format seems invalid :slightly_frowning_face:

Please feel free to check the contribution instruction in the [readme](https://github.com/KiFoundation/ki-testnet-challenge/tree/main/contributions/relayers) and to commit the necessary changes to this PR.

The contribution content will be reviewed later.

**Review by qf3l3k — COMMENTED** [review]
Updated. Now all should be fine :)

**Comment by qf3l3k** [comment]
Tx list fixed.

**Review by qf3l3k — COMMENTED** [review]
Tx formatting fixed.

**Comment by qf3l3k** [comment]
Tx format fixed.

**Review by TarekAwwad — APPROVED** [review]
Thank you for contributing! The contribution format is valid :+1:
The contribution content will be reviewed later.

**Pull request merged**
