### PR TITLE
Darkstaff88-darkstaff88node.json

### PR DESCRIPTION
**Pull request by Darkstaff88**

### CODE REVIEW

**Review by TarekAwwad — CHANGES_REQUESTED** [review]
Thank you for contributing! The contribution format seems invalid :slightly_frowning_face: 

Please feel free to check the contribution instruction in the [readme](https://github.com/KiFoundation/ki-testnet-challenge/tree/main/contributions/relayers) and to commit the necessary changes to this PR. 

The contribution content will be reviewed later.

**Comment by IamJuly** [comment]
Hey Tarek! i actually don't get why my format is wrong, maybe because of wrong 'additional Comments'? i changed it. Let me please know if it's ok :)

**Comment by TarekAwwad** [comment]
Please do not remove the template file.

**Comment by Darkstaff88** [comment]
is it ok now?:)

**Review by TarekAwwad — APPROVED** [review]

**Pull request merged**
