### PR TITLE
Create svv28-sw33_KiChain_node.json

### PR DESCRIPTION
**Pull request by svv28**
This is my second try of IBC relayer.
As soon as KiChaun Explorer doesn't show my transactions 11.09, i thought, that i did something wrong. so i made it whole from the scratch
but first transactions were at 11.09 and 12.09, as you can see from hashs.

Link to description:
https://github.com/svv28/ki-testnet-challenge/blob/main/contributions/relayers/README_Umee_KiChain_IBC_sw33_KiChain_node.md

### CODE REVIEW

**Comment by svv28** [comment]
This is my second try of IBC relayer.
As soon as KiChaun Explorer doesn't show my transactions 11.09, i thought, that i did something wrong. so i made it whole from the scratch
but first transactions were at 11.09, as you can see from  hashs.

**Comment by TarekAwwad** [comment]
Thank you for contributing! Unfortunately, this PR has been created after the deadline and cannot be considered.

**Comment by svv28** [comment]
Look, Tarek,  i totally understand, that i missed deadline and i dont whant to argue... but as i mentioned, all necessary amount transactions were made before block 304300. you can check it by their hashes. and the only reason, i hadn't made pull request in time is that Ki explorer didn't show them and i have to re deploy Umee node and reinstall the relayer.
I really hope, that you take it into account, and at least proces my transactions as partially maded testnet challange.
best regards!

**Comment by svv28** [comment]
> 
> 
> Thank you for contributing! Unfortunately, this PR has been created after the deadline and cannot be considered.

Dear, Tarek,  i totally understand, that i missed deadline and i dont whant to argue... but as i mentioned, all necessary amount transactions were made before block 304300. you can check it by their hashes. and the only reason, i hadn't made pull request in time is that Ki explorer didn't show them and i have to re deploy Umee node and reinstall the relayer.
I really hope, that you take it into account, and at least process my transactions as partially made testnet challenge.
best regards!

**Pull request closed without merging**
